### ISSUE TITLE
..

### ISSUE THREAD

**Issue by devwoojin** [mans0n/mans0n.github.io#2]

**Comment by devwoojin** [comment]
close

**Comment by mans0n** [comment]
@devwoojin 미안합니다. 최근에 한동안 깃헙 알림을 확인하지 않았더니 이슈가 올라온지도 모르고 있었네요. (메일로도 알림설정 해뒀는데 왜 안 온건지...)
아마 이미 해결하셨을 것 같지만, 혹시 아직 문의사항이 있다면 제 커밋에 적힌 메일주소로 메일 주세요. 빠르게 답장드릴 수 있을진 모르겠지만 확인은 그쪽이 더 빠를 겁니다.

**Comment by devwoojin** [comment]
안녕하세요.
개인적인 공간에 흔적을 남겨서 민폐가 되나 싶어서 글을 지웠었습니다.
커밋에 적힌 메일 주소를 찾지 못했습니다. ㅠㅠ.
지운글에 답변까지 해주시고 대단히 감사합니다~
